name: flutter_dev
description: flutter base app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf

  - family: Zeyada
    fonts:
      - asset: fonts/Zeyada-Regular.ttf

  - family: JetBrainsMono
    fonts:
      - asset: fonts/JetBrainsMono-VariableFont_wght.ttf

  - family: MajorMonoDisplay
    fonts:
      - asset: fonts/MajorMonoDisplay-Regular.ttf

  - family: ShareTechMono
    fonts:
      - asset: fonts/ShareTechMono-Regular.ttf

  - family: SourceCodePro
    fonts:
      - asset: fonts/SourceCodePro-VariableFont_wght.ttf

  - family: Graduate
    fonts:
      - asset: fonts/Graduate-Regular.ttf

  - family: Iceland
    fonts:
      - asset: fonts/Iceland-Regular.ttf

  - family: SpecialElite
    fonts:
      - asset: fonts/SpecialElite-Regular.ttf